<a href="https://colab.research.google.com/github/estefasilva/ApuntesLogica/blob/main/googlecolab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [13]:
edades = [34,45,46]
print (edades)


[34, 45, 46]


In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns



In [10]:
edades =np.array ([34,45,46])
print (edades)


[34 45 46]


In [11]:
print(type(edades))

<class 'numpy.ndarray'>


In [15]:
#esto es un coomentario
#estamos usando el atributo shape para obtener eltamaño del array(vector)w3school Numpy tutorial
edades.shape

AttributeError: 'list' object has no attribute 'shape'

In [14]:
#sort ordena de manera ascendente
edades.sort
print (edades)

[34, 45, 46]


In [16]:
#esto es un coomentario
#estamos usando el atributo shape para obtener eltamaño del array(vector)w3school Numpy tutorial https://www.w3schools.com/python/numpy/numpy_array_sort.asp
edades [::-1].sort()

In [17]:
#slicing  es muy importante  CONSULTAR
print(edades[0:2])

[34, 45]


In [18]:
#muestra de la lista desde el indice 2 en adelante
print(edades[2:])

[46]


In [19]:
print(edades[:])

[34, 45, 46]


In [20]:
print(edades[:-1:])

[34, 45]


In [21]:
#INDEXADO=>  POSICION A LA QUE PUEDO INGRESAR
print(edades[0])

34


In [22]:
edades2 = np.array([45,51,34,44])

In [23]:
## estamos usando join que lo que hace es unir dos o mas ndarray

edades_todas = np.concatenate((edades, edades2))
print(edades_todas)

[34 45 46 45 51 34 44]


#join de array


```
# Tiene formato de código
```



In [24]:
##podemos hacer busquedas en los ndarray
print(np.where(edades_todas == 45))

(array([1, 3]),)


In [26]:
edades_todas.searchsorted(45)


1

In [27]:
edades_todas.searchsorted(51)

7

como insertar un valor en un array

In [34]:
edades_todas = np.insert(edades_todas, 8, 70)


IndexError: index 8 is out of bounds for axis 0 with size 7

In [33]:
edades_todas.sort()
print(edades_todas)

[34 34 44 45 45 46 51]


In [36]:
db_edades = np.array([21, 34, 34,7, 44, 45, 45, 10, 46, 17, 51, 70])
print(db_edades)

[21 34 34  7 44 45 45 10 46 17 51 70]


In [51]:
array_i = []

for i in db_edades:
  if i < 18:
    array_i.append(False)
  else:
    array_i.append(True)
print(array_i)
print(len(array_i))

[False, False, False, True, True, True, True, True, True, True, True, True]
12


In [37]:
db_edades.sort()
print(db_edades)

[ 7 10 17 21 34 34 44 45 45 46 51 70]


#Array de dos dimensiones

In [52]:
array_2d = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
array_3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
